name: chatsx
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  dio: ^5.2.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.13.6
  shared_preferences: ^2.2.2
  package_info: ^2.0.2
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.9
  flutter_easyloading: ^3.0.5
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.4
#  flutter_facebook_auth: ^6.0.3
  dots_indicator: ^3.0.0
  flutter_verification_code: ^1.1.7
  url_launcher: ^6.2.5
  firebase_storage: ^11.5.6
  image_picker: ^1.0.5
  photo_view: ^0.14.0
  agora_rtc_engine: ^6.2.6
  just_audio: ^0.9.36
  permission_handler: ^11.1.0
  pull_to_refresh: ^2.0.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
